# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tagger}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nando Vieira"]
  s.date = %q{2010-10-05}
  s.description = %q{Add tagging support for Rails apps}
  s.email = %q{fnando.vieira@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
     "Gemfile.lock",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/tagger.rb",
     "lib/tagger/active_record.rb",
     "lib/tagger/generator.rb",
     "lib/tagger/helper.rb",
     "lib/tagger/railtie.rb",
     "lib/tagger/tag.rb",
     "lib/tagger/tagging.rb",
     "lib/tagger/version.rb",
     "spec/fixtures/categories.yml",
     "spec/fixtures/links.yml",
     "spec/fixtures/posts.yml",
     "spec/fixtures/tags.yml",
     "spec/helpers/helper_spec.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb",
     "spec/support/config/boot.rb",
     "spec/support/config/database.yml",
     "spec/support/log/test.log",
     "spec/support/models.rb",
     "spec/tagger_spec.rb",
     "tagger.gemspec",
     "templates/taggings.rb",
     "templates/tags.rb"
  ]
  s.homepage = %q{http://github.com/fnando/tagger}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Add tagging support for Rails apps}
  s.test_files = [
    "spec/helpers/helper_spec.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb",
     "spec/support/config/boot.rb",
     "spec/support/models.rb",
     "spec/tagger_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
  end
end

